server changes to add speed API
transitmatters/t-performance-dash pull request #399
Opened 2023-03-25 19:35 UTC by PatrickCleary

Add /api/speed route

Also a small fix to my old alerts code

Also autoformatter redid some json files. Can undo if we don't want that.

2023-03-26 14:01 UTC, skaplan-dev approved these changes

2023-04-01 16:56 UTC, austinjpaul requested changes
We need to be a little more careful with the params users can pass to us, but otherwise looks great!

2023-04-01 16:56 UTC, austinjpaul commented on server/chalicelib/dynamo.py
> +        return {"Error": "Invalid Query - too many items requested."}
I know we don't do this currently, but I would love for input validation to be done in app.py, where we can raise a 4xx status code (Chalice has some builtins to help here I think) instead of a 5xx when the user input is wrong.

2023-04-01 16:56 UTC, austinjpaul commented on server/chalicelib/dynamo.py
> +    response = table.query(**query_params)
I'm partial to replacing this with the (IMO) more readable form:
```
from boto3.dynamodb.conditions import Key
...
response = table.query(KeyConditionExpression=Key("line").eq(line) & Key("date").between(start_date, end_date))
```

2023-04-01 16:56 UTC, austinjpaul commented on server/chalicelib/dynamo.py
> +AGG_TO_CONFIG_MAP = {
A comment explaining the delta here wouldn't be amiss.

2023-04-01 16:56 UTC, austinjpaul commented on server/chalicelib/dynamo.py
> +def query_speed_tables(params):
In conjunction with validating params in app.py (see below), this function should take distinct arguments (line, start_date, end_date). 
(Right now, user can specify secret params that get passed straight through to `table.query()`. not good!)

2023-04-01 16:56 UTC, austinjpaul commented on server/chalicelib/dynamo.py
> +AGG_TO_CONFIG_MAP = {
"here", well this dict should maybe move inside get_speed() in app.py with the rest of validation.

2023-04-01 17:00 UTC, austinjpaul commented on server/chalicelib/dynamo.py
> +def query_speed_tables(params):
oh, and `table` i suppose. Someday if we add a bunch more tables we might want to separate out calls to each, but this is good for now.

2023-04-02 22:36 UTC, austinjpaul approved these changes
looks great, thanks!!

2023-04-02 22:39 UTC, merged