V4/nav rework
transitmatters/t-performance-dash pull request #458
Opened 2023-04-06 18:34 UTC by PatrickCleary

Waiting on #454 and #456

2023-04-06 21:00 UTC, devinmatte commented
Initial thoughts (some of the same discussed in slack)

Personally I don't think we should seperate out range and single day views
![Screenshot 2023-04-06 at 4 41 55 PM](https://user-images.githubusercontent.com/9310513/230492487-a191bbb0-4f63-4442-91f5-4a075eb03e38.png)

As @skaplan-dev brought up, speed might not be the most useful to a rider, so making the metric front and center might not be the most advisable. Although, we can discuss this with more of labs to determine order
![Screenshot 2023-04-06 at 4 47 11 PM](https://user-images.githubusercontent.com/9310513/230492491-65e34b7d-7db6-434b-8e37-52b2725ee270.png)

I also noticed that dates disappear from query params when jumping between pages. Ideally we'd persist the query params even if a page ignores them. Same with preferences between range and single select, like we do today

2023-04-06 21:29 UTC, devinmatte commented
One minor, nitpicky, thought towards not separating singe/range is when separated on my large monitor, I had to scroll to see all option in the sidebar. Less options on the sidebar brings more things above the fold for the average user
![Screenshot 2023-04-06 at 4 26 59 PM](https://user-images.githubusercontent.com/9310513/230497503-5c41b1d2-37e8-4044-af68-bb37d92266bc.png)

2023-04-09 22:50 UTC, devinmatte commented
Notes so far:

### 1: Love the floating datepicker
<img width="713" alt="Screenshot 2023-04-09 at 6 32 55 PM" src="https://user-images.githubusercontent.com/9310513/230799620-94f0286e-1bf7-4034-b57e-89f32bf6eace.png">

### 2: One bug with the tabs
One bug with the tabs, and maybe with the concept, is sometimes it can get into a single date selection state, despite selecting range, which looks much weirder than if you didn't have the tabs

<img width="1000" alt="Screenshot 2023-04-09 at 6 33 57 PM" src="https://user-images.githubusercontent.com/9310513/230799661-f8fc0224-eb61-4f52-a2ab-43972485446e.png">

### 3: Overview page should have white widget borders
They should have the same widget borders, or, one large white border for the section. It living on the background feels weird (I know this might be a different problem to solve)

<img width="981" alt="Screenshot 2023-04-09 at 6 36 11 PM" src="https://user-images.githubusercontent.com/9310513/230799734-893557f3-cf8d-4689-b4e4-aa04f48f78e6.png">

### 4: Two overview pages
Not a fan of both of these pages being called the same thing. Overview works in the main `line` section, but I don't love the name for the Trip section

<img width="248" alt="Screenshot 2023-04-09 at 6 42 58 PM" src="https://user-images.githubusercontent.com/9310513/230799875-93b475ad-6ff2-4749-9c14-3743db8533b6.png">

### 5: Alert taking full width while speed doesn't
It's odd to me that they're different sizes. Either they'd sit next to each other, or, both be full width

<img width="982" alt="Screenshot 2023-04-09 at 6 48 33 PM" src="https://user-images.githubusercontent.com/9310513/230800014-5700d7a1-4740-4a5b-88d7-2410b52a1102.png">

2023-04-10 13:36 UTC, PatrickCleary commented
> 1: Love the floating datepicker
😁

> 2: One bug with the tabs

True, though I think we could add a way to prevent this



> 3: Overview page should have white widget borders

Agreed

> ### 4: Two overview pages

Yea, I think you're right. I'm open to suggestions for other names.


> ### 5: Alert taking full width while speed doesn't

Yea, I agree. Ideally we will have a third thing there soon and can adjust these accordingly. I was thinking full alerts then two half-size below. Although now idk if alerts needs that much space. For now I can make them all full-width

2023-04-11 01:48 UTC, devinmatte commented on common/components/inputs/DateSelection/DatePickers.tsx
I am not convinced that we should remove the code for a date picker to be swapped between single and range. It may be too much work, but I'd prefer a prop that disables the setting instead of removing the code

2023-04-11 16:55 UTC, devinmatte commented
<img width="992" alt="Screenshot 2023-04-11 at 12 55 19 PM" src="https://user-images.githubusercontent.com/9310513/231235072-937ecefa-0cb2-4428-abe6-c3d3ac83a442.png">
🐛

2023-04-11 17:10 UTC, devinmatte approved these changes
I did as good of a pass as I felt I could. I've noted the errors I saw that should be fixed either in this PR or in https://github.com/transitmatters/t-performance-dash/pull/472

2023-04-11 17:12 UTC, PatrickCleary commented on common/layouts/DashboardLayout.tsx
> +    if (section === 'overview') return <OverviewDateSelection />;
In this PR or new issue?

2023-04-11 17:15 UTC, devinmatte commented on common/utils/router.tsx
> +const getParams = (params) => {
Maybe a `Partial<QueryParams>`? But that might be too much effort. We can leave it for now. I do want to add more TS rules later, but we can follow up on that

2023-04-11 17:17 UTC, PatrickCleary commented on common/utils/router.tsx
> +const getParams = (params) => {
Discussed in https://github.com/transitmatters/t-performance-dash/pull/458#discussion_r1162801742

2023-04-11 17:19 UTC, devinmatte commented
I should note a caveat to my review, that I am still not a fan of the tab `range` vs `single`. I much prefer our original method for date selection changes. I am however fine with merging in this manor since it is easily reversible should the majority of labs agree

2023-04-11 17:19 UTC, PatrickCleary commented
https://github.com/transitmatters/t-performance-dash/pull/458#issuecomment-1503756299

Will be fixed in next PR

2023-04-11 17:23 UTC, PatrickCleary commented on modules/dashboard/DataPageHeader.tsx
> +  const { line, page } = useDelimitatedRoute();
Don't need any of the `range` state because the date picker lives in the `DashboardLayout` now and is self-contained.

2023-04-11 17:25 UTC, devinmatte commented on common/layouts/DashboardLayout.tsx
> +    if (section === 'overview') return <OverviewDateSelection />;
We can include it as part of https://github.com/transitmatters/t-performance-dash/issues/401

2023-04-11 17:31 UTC, PatrickCleary commented on modules/navigation/BusSelection.tsx
This is mostly preexisting code that was in `modules/navigation/desktop/BusDropdownItem.tsx`

2023-04-11 17:31 UTC, PatrickCleary commented on modules/navigation/LineSelection.tsx
Line Selection. Mostly reused old line selection. Could use a bit more UI work.
![Screen Shot 2023-04-11 at 1 25 15 PM](https://user-images.githubusercontent.com/46229349/231241463-61713d48-0594-4827-9c76-050b02c1c26d.png)

2023-04-11 17:31 UTC, PatrickCleary commented on modules/navigation/RangeTabs.tsx
Attempt to differentiate more between `range` and `single day` data types. As first suggested by @austinjpaul.

This change is definitely undecided. I put it in this pr just so we could try it out and demo it on Thursday. I think we'll be able to get a better sense for it if we can see it working. If consensus is opposed, will revert.

I also think maybe `range` and `single day` are not the best names. Because the real difference is `per day aggregates` vs. `per-trip` data. So maybe new names would be better.

![Screen Shot 2023-04-11 at 1 26 21 PM](https://user-images.githubusercontent.com/46229349/231241696-7171e813-064a-4846-b3c9-bb8997c45515.png)

2023-04-11 17:31 UTC, PatrickCleary commented on modules/navigation/SidebarTabs.tsx
Bulk of the changes. Open to naming, icon, and ordering suggestions for anything. These were all just what I put in to start.
![Screen Shot 2023-04-11 at 1 29 44 PM](https://user-images.githubusercontent.com/46229349/231242470-62a33fb5-5f3a-4f51-b1ac-8168037fc45e.png)

2023-04-11 17:35 UTC, devinmatte commented on modules/navigation/SidebarTabs.tsx
I feel like some variation of `Trip Explorer`, `Explore` is better than using `Overview` in two spots.

As for ordering I think we had discussed an order above that might be more valuable to a user
![image](https://user-images.githubusercontent.com/9310513/231243592-68d0c2c4-671c-4d0e-a662-063ce1a16a71.png)

2023-04-11 17:36 UTC, PatrickCleary commented on modules/navigation/SidebarTabs.tsx
I like `Explore`. And just updated the ordering 👍

2023-04-11 17:38 UTC, PatrickCleary commented on modules/navigation/SidebarTabs.tsx
I was also using `Trip Overview` as the title. What about that?

2023-04-11 17:39 UTC, PatrickCleary commented on modules/navigation/SidebarTabs.tsx
`Summary` ?

2023-04-11 18:07 UTC, devinmatte commented on modules/navigation/SidebarTabs.tsx
Trip Explorer or Trip Summary both seem reasonable. Not sure on final naming

2023-04-12 00:11 UTC, skaplan-dev requested changes
## 
Took a first pass. I think this would be a lot cleaner if we had some more containers that were checking bus/subway mode. Then you wouldn't have so many if statements all over the place checking `line`/etc.

Also pulled this down locally and here's a list of things that aren't working for me.

- Default route broken
- Speed widget broken
- Station picker under explore doesn’t change for headways / traveltimes when switching line
- Bus page is broken
- Aggregate apis aren’t working for me locally

## Questions
- Can you explain having travel times / headways / dwells under trips and line?

## Suggestions
- Tooltips on disabled nav items?

2023-04-12 00:11 UTC, skaplan-dev commented on modules/dashboard/Today.tsx
> +        {tab === 'Subway' && line !== 'GL' && <Speed />}
i feel like I'm seeing this repeated a lot. (checking if we are in subway view)
Maybe we should separate Subway and Bus `Today` views?

2023-04-12 00:11 UTC, skaplan-dev commented on modules/dashboard/Today.tsx
> +        {tab === 'Subway' && line !== 'GL' && <Speed />}
we also have a variable storing `line !==  "GL"` already above with canShowSlowZonesMap.

2023-04-12 00:11 UTC, skaplan-dev commented on modules/navigation/SideNavigation.tsx
> +  setSidebarOpen?: React.Dispatch<React.SetStateAction<boolean>>;
why is this optional?

2023-04-12 01:43 UTC, PatrickCleary commented on modules/navigation/BusNavMenu.tsx
> +  setSidebarOpen?: React.Dispatch<React.SetStateAction<boolean>>;
It's only needed on the mobile nav sidebar. https://github.com/transitmatters/t-performance-dash/blob/dashboard-v4/modules/navigation/desktop/SideNavBar.tsx#L91-L112

2023-04-12 01:51 UTC, PatrickCleary commented on modules/navigation/RangeTabs.tsx
> +  const selected = query.single === 'yes' ? 1 : 0;
Just signifies whether the page is in `single day` mode. I don't have a great idea for what to name it instead. 
single=`true`?
type=`singleday`?

2023-04-12 02:00 UTC, PatrickCleary commented
Thanks for the thorough review  @skaplan-dev  😁
I think you make a good point about checking for line. I will look into your suggestion - my immediate thought is that since most components just pull the line from `useDelimitatedRoute()` I would think any prior gating on `line` wouldn't be known to the component. I could maybe do something inside the router? idk. Do you have any ideas? or am I missing something?
 
 Also in top-level pages, they would have no way of being gated other than checking the params I would think.

> * Default route broken

fixed.

> * Speed widget broken

I can't seem to replicate this

> * Station picker under explore doesn’t change for headways / traveltimes when switching line

I can probably figure this out, but the next change is overhauling the station selector and then it will pull values from the query params. So that will fix it. Do you think it needs to be fixed in this PR?

> * Bus page is broken

Preexisting bug:
https://github.com/transitmatters/t-performance-dash/issues/452

> * Aggregate apis aren’t working for me locally

I also haven't been able to reproduce this

> * Can you explain having travel times / headways / dwells under trips and line?

Do you mean why they are not under trips and line? If so, the pages are organized by the parameters they take. The `line` section is station-agnostic. The `trips` section has the widgets which require a station to be chosen. Another reason to separate them is the "expected" date ranges are very different. A date range of a year or more in the `line` section is to be expected, whereas it will be very slow or not work in the `trips` section. If someone is clicking around in the `line` section then goes to "headways" and nothing loads, that will be a source of confusion/friction.

> * Why are we using `GL` and `Green` / etc . Shouldn't we stick to one denominator for the line? It seems like they're describing the same thing

https://github.com/transitmatters/t-performance-dash/pull/459



> * Tooltips on disabled nav items?

All for it. I can create an issue? https://github.com/transitmatters/t-performance-dash/issues/476

2023-04-12 02:00 UTC, PatrickCleary commented on modules/navigation/SidebarTabs.tsx
> +  setSidebarOpen?: React.Dispatch<React.SetStateAction<boolean>>;
answered aboce

2023-04-12 14:40 UTC, merged