add histogram back
transitmatters/t-performance-dash pull request #749
Opened 2023-07-12 16:53 UTC by PatrickCleary

## Motivation

Forgot to add the headways histogram back.

## Changes

Adds headways histogram back.
Removing the grid in #748 which makes the whitespace at the botom go away.
![Screenshot 2023-07-12 at 12 52 53 PM](https://github.com/transitmatters/t-performance-dash/assets/46229349/a6bc16b1-d3bf-43d3-9557-f5a699c0700e)

## Testing Instructions

2023-07-12 17:45 UTC, skaplan-dev requested changes
We should have this work irrespective of #748 (the whitespace)

2023-07-12 18:17 UTC, PatrickCleary commented
I don't think that is realistic. To do that we need all the charts be the exact same height, which is the issue with the grid.

2023-07-12 20:43 UTC, devinmatte commented on modules/tripexplorer/SubwayTripGraphs.tsx
> +              subtitle="Time spent at station"
This isn't correct, unless you mean "time rider spends at station waiting for train"

2023-07-12 20:44 UTC, PatrickCleary commented on modules/tripexplorer/SubwayTripGraphs.tsx
> +              subtitle="Time spent at station"
whoops. Good catch.

2023-07-13 23:00 UTC, devinmatte commented
I don't love using "histogram" in the visible display text. Maybe "distribution"?

2023-07-13 23:07 UTC, devinmatte approved these changes

2023-07-13 23:14 UTC, merged