add csv download link to speed, prediction accuracy, service, ridership
transitmatters/t-performance-dash pull request #935
Opened 2024-01-11 19:17 UTC by cdwhitt

## Motivation

Commonly used widgets need a link to download a .csv file so people can use our data in research without needing to reach out to us [#906](https://github.com/transitmatters/t-performance-dash/issues/906)

## Changes

## Testing Instructions

2024-01-11 19:47 UTC, skaplan-dev reviewed
Could you add some images and more information to the PR description?

It also looks like there were some moving around of `ChartBorder`. Were we using it inconsistently in places?

2024-01-11 19:47 UTC, skaplan-dev commented on modules/predictions/charts/PredictionsGraph.tsx
> +            data={dataWithPercentage as unknown as (DataPoint | AggregateDataPoint)[]}
where do we lose type information for this?

2024-01-12 00:42 UTC, idreyn requested changes
Overall looks pretty good to me! My only hard request for changes is that we loosen the `data` type that `<DownloadButton>` accepts — it should work for any `Record<string, any>[]`, and if we use that instead, we won't need to coerce TypeScript with the `as unknown as X` casts (marked with ❗ in my comments)

Thanks for diving in to add this. This is an excellent first contribution!

2024-01-12 00:42 UTC, idreyn commented on common/components/buttons/DownloadButton.tsx
>    data: (DataPoint | AggregateDataPoint)[];
I think we can loosen this type to something like `Record<string, any>[]`.

2024-01-12 00:42 UTC, idreyn commented on common/utils/csv.ts
> +export function filename(
This is a pretty good abstraction. Few thoughts:

- It could have a more specific name, like `getCsvFilename`
- The `bothStops` argument should be optional since many callers don't need to think about stops at all
- With this many arguments I'd consider letting users pass in an object:

```ts
type GetCsvFilenameOptions = {
  datasetName: string;
  startDate: string;
  endDate: string;
  location?: Location;
  includeBothStopsForLocation?: Location;
}

const getCsvFilename = (options: GetCsvFilenameOptions) => { ... }
```

2024-01-12 00:42 UTC, idreyn commented on modules/predictions/utils/utils.ts
> +export const addAccuracyPercentageToData = (data: TimePredictionWeek[]) => {
Maybe this belongs in the csv utils since it's most directly related to that.

2024-01-12 00:42 UTC, idreyn commented on modules/speed/utils/utils.ts
> +export const addMPHToSpeedData = (data: DeliveredTripMetrics[]) => {
Also possibly belongs in the csv utils

2024-01-12 00:42 UTC, idreyn commented on modules/ridership/RidershipGraph.tsx
> +              data={data as unknown as (DataPoint | AggregateDataPoint)[]}
❗ We should loosen the type of `data` so we don't need these casts.

2024-01-12 00:42 UTC, idreyn commented on modules/service/ServiceGraph.tsx
> +            data={data as unknown as (DataPoint | AggregateDataPoint)[]}
❗ Here too

2024-01-12 00:42 UTC, idreyn commented on modules/speed/SpeedGraph.tsx
> +            data={dataWithMPH as unknown as (DataPoint | AggregateDataPoint)[]}
❗ Here too

2024-01-13 22:03 UTC, cdwhitt commented on modules/ridership/RidershipGraph.tsx
> +              data={data as unknown as (DataPoint | AggregateDataPoint)[]}
Thanks for commenting on this! I'm working on changing now, but having some issues locally that I posted about in the slack channel. I made it so the `DownloadButton` can optionally accept multiple data types.

2024-01-13 22:03 UTC, cdwhitt commented on modules/service/ServiceGraph.tsx
> +            data={data as unknown as (DataPoint | AggregateDataPoint)[]}
Same as above.

2024-01-13 22:03 UTC, cdwhitt commented on modules/speed/SpeedGraph.tsx
> +            data={dataWithMPH as unknown as (DataPoint | AggregateDataPoint)[]}
Same as above.

2024-01-13 22:42 UTC, cdwhitt commented
I responded to probably half of the comments here, will finish up tomorrow (1/14). @skaplan-dev @idreyn

2024-01-13 22:52 UTC, cdwhitt commented
> Could you add some images/gifs and more information to the PR description?
> 
> It also looks like there were some moving around of `ChartBorder`. Were we using it inconsistently in places?

Also wanted to mention, this needed to be moved up a level as it caused some inconsistency when I added the DownloadButton to one of the widgets. I checked, and moving it didn't affect anything else.

2024-01-14 21:48 UTC, cdwhitt commented on common/utils/csv.ts
> +export function filename(
I'm a little confused by this - what's the need for `includeBothStopsForLocation` if we already have an optional `location` param that's the same shape?

2024-01-15 13:34 UTC, idreyn commented on common/utils/csv.ts
> +export function filename(
Oh, I mistyped that. I meant `includeBothStopsForLocation: boolean`. That's just me riffing on a potentially clearer name for `bothStops`.

2024-01-15 20:57 UTC, idreyn commented on common/components/buttons/DownloadButton.tsx
> +  data: Record<string, any>[];
fyi: `unknown` should work here instead of `any` and then the linter won't complain.

2024-01-15 20:59 UTC, idreyn approved these changes
Looking great! Please remove the remaining `as unknown as X` casts before you merge, now that the `data` prop has a more permissive type, pretty much anything we throw at it should work.

2024-01-15 21:33 UTC, merged

2024-01-15 23:54 UTC, devinmatte commented on common/components/buttons/DownloadButton.tsx
> +  data: Record<string, any>[];
Yeah in general we should prefer unknown as it throws more warnings whereas any basically disables checks.
Probably should add some linting for prefer unknown